CC=gcc
CFLAGS=-W -Wall -ansi -pedantic -std=c99
LDFLAGS=
EXEC=comXbee

all: $(EXEC)

comXbee: comXbee.o checksum.o
	$(CC) -o comXbee comXbee.o checksum.o $(LDFLAGS)


checksum.o: checksum.c  
	$(CC) -o checksum.o -c checksum.c $(CFLAGS)

comXbee.o: comXbee.c checksum.h 
	$(CC) -o comXbee.o -c comXbee.c $(CFLAGS)

clean:
	rm -rf *.o
